//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartRateMonitor.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeartRateMonitor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }

        internal static string TimeAxis {
            get {
                return ResourceManager.GetString("TimeAxis", resourceCulture);
            }
        }

        internal static string BtnScan {
            get {
                return ResourceManager.GetString("BtnScan", resourceCulture);
            }
        }

        internal static string BtnScanning {
            get {
                return ResourceManager.GetString("BtnScanning", resourceCulture);
            }
        }

        internal static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }

        internal static string BtnAutoReconnect {
            get {
                return ResourceManager.GetString("BtnAutoReconnect", resourceCulture);
            }
        }

        internal static string BtnShowAll {
            get {
                return ResourceManager.GetString("BtnShowAll", resourceCulture);
            }
        }

        internal static string BtnRecord {
            get {
                return ResourceManager.GetString("BtnRecord", resourceCulture);
            }
        }

        internal static string BtnRecording {
            get {
                return ResourceManager.GetString("BtnRecording", resourceCulture);
            }
        }

        internal static string BtnClearChart {
            get {
                return ResourceManager.GetString("BtnClearChart", resourceCulture);
            }
        }

        internal static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }

        internal static string BtnConnect {
            get {
                return ResourceManager.GetString("BtnConnect", resourceCulture);
            }
        }

        internal static string BtnDisconnect {
            get {
                return ResourceManager.GetString("BtnDisconnect", resourceCulture);
            }
        }

        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }

        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }

        internal static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }

        internal static string BtnNo {
            get {
                return ResourceManager.GetString("BtnNo", resourceCulture);
            }
        }

        internal static string TrayShow {
            get {
                return ResourceManager.GetString("TrayShow", resourceCulture);
            }
        }

        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        internal static string TrayMinimized {
            get {
                return ResourceManager.GetString("TrayMinimized", resourceCulture);
            }
        }

        internal static string HeaderScanControl {
            get {
                return ResourceManager.GetString("HeaderScanControl", resourceCulture);
            }
        }

        internal static string HeaderDiscoveredDevices {
            get {
                return ResourceManager.GetString("HeaderDiscoveredDevices", resourceCulture);
            }
        }

        internal static string HeaderRealtimeData {
            get {
                return ResourceManager.GetString("HeaderRealtimeData", resourceCulture);
            }
        }

        internal static string ColDevice {
            get {
                return ResourceManager.GetString("ColDevice", resourceCulture);
            }
        }

        internal static string ColHeartRate {
            get {
                return ResourceManager.GetString("ColHeartRate", resourceCulture);
            }
        }

        internal static string ColBattery {
            get {
                return ResourceManager.GetString("ColBattery", resourceCulture);
            }
        }

        internal static string ColColor {
            get {
                return ResourceManager.GetString("ColColor", resourceCulture);
            }
        }

        internal static string ColAction {
            get {
                return ResourceManager.GetString("ColAction", resourceCulture);
            }
        }

        internal static string LabelYAxisRange {
            get {
                return ResourceManager.GetString("LabelYAxisRange", resourceCulture);
            }
        }

        internal static string LabelMinValue {
            get {
                return ResourceManager.GetString("LabelMinValue", resourceCulture);
            }
        }

        internal static string LabelMaxValue {
            get {
                return ResourceManager.GetString("LabelMaxValue", resourceCulture);
            }
        }

        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        internal static string StatusScanningStopped {
            get {
                return ResourceManager.GetString("StatusScanningStopped", resourceCulture);
            }
        }

        internal static string StatusDetectingBluetooth {
            get {
                return ResourceManager.GetString("StatusDetectingBluetooth", resourceCulture);
            }
        }

        internal static string StatusScanningComplete {
            get {
                return ResourceManager.GetString("StatusScanningComplete", resourceCulture);
            }
        }

        internal static string StatusScanningDevices {
            get {
                return ResourceManager.GetString("StatusScanningDevices", resourceCulture);
            }
        }

        internal static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }

        internal static string ErrorBluetoothNotReady {
            get {
                return ResourceManager.GetString("ErrorBluetoothNotReady", resourceCulture);
            }
        }

        internal static string ErrorBluetoothScanFailed {
            get {
                return ResourceManager.GetString("ErrorBluetoothScanFailed", resourceCulture);
            }
        }

        internal static string ErrorConnectFailed {
            get {
                return ResourceManager.GetString("ErrorConnectFailed", resourceCulture);
            }
        }

        internal static string ErrorNoDeviceForExport {
            get {
                return ResourceManager.GetString("ErrorNoDeviceForExport", resourceCulture);
            }
        }

        internal static string ErrorInvalidNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidNumber", resourceCulture);
            }
        }

        internal static string ErrorMinMustBeLessThanMax {
            get {
                return ResourceManager.GetString("ErrorMinMustBeLessThanMax", resourceCulture);
            }
        }

        internal static string ErrorConnectFirst {
            get {
                return ResourceManager.GetString("ErrorConnectFirst", resourceCulture);
            }
        }

        internal static string ConfirmClearChart {
            get {
                return ResourceManager.GetString("ConfirmClearChart", resourceCulture);
            }
        }

        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }

        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }

        internal static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }

        internal static string ExportTypeHistory {
            get {
                return ResourceManager.GetString("ExportTypeHistory", resourceCulture);
            }
        }

        internal static string ExportTypeSnapshot {
            get {
                return ResourceManager.GetString("ExportTypeSnapshot", resourceCulture);
            }
        }

        internal static string ExportSelectFields {
            get {
                return ResourceManager.GetString("ExportSelectFields", resourceCulture);
            }
        }

        internal static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }

        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }

        internal static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }

        internal static string BleGetDeviceFailed {
            get {
                return ResourceManager.GetString("BleGetDeviceFailed", resourceCulture);
            }
        }

        internal static string BleGetGattFailed {
            get {
                return ResourceManager.GetString("BleGetGattFailed", resourceCulture);
            }
        }

        internal static string BleHeartRateSubscribeFailed {
            get {
                return ResourceManager.GetString("BleHeartRateSubscribeFailed", resourceCulture);
            }
        }

        internal static string BleConnected {
            get {
                return ResourceManager.GetString("BleConnected", resourceCulture);
            }
        }

        internal static string BleDisconnected {
            get {
                return ResourceManager.GetString("BleDisconnected", resourceCulture);
            }
        }

        internal static string BleReconnectSuccess {
            get {
                return ResourceManager.GetString("BleReconnectSuccess", resourceCulture);
            }
        }

        internal static string BleReconnectFailed {
            get {
                return ResourceManager.GetString("BleReconnectFailed", resourceCulture);
            }
        }

        internal static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }

        internal static string ColorOrange {
            get {
                return ResourceManager.GetString("ColorOrange", resourceCulture);
            }
        }

        internal static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }

        internal static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }

        internal static string ColorPurple {
            get {
                return ResourceManager.GetString("ColorPurple", resourceCulture);
            }
        }

        internal static string ColorBlack {
            get {
                return ResourceManager.GetString("ColorBlack", resourceCulture);
            }
        }

        internal static string FieldDevice {
            get {
                return ResourceManager.GetString("FieldDevice", resourceCulture);
            }
        }

        internal static string FieldHeartRate {
            get {
                return ResourceManager.GetString("FieldHeartRate", resourceCulture);
            }
        }

        internal static string FieldRR {
            get {
                return ResourceManager.GetString("FieldRR", resourceCulture);
            }
        }

        internal static string FieldDfaAlpha1 {
            get {
                return ResourceManager.GetString("FieldDfaAlpha1", resourceCulture);
            }
        }

        internal static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }

        internal static string ExportBtnExport {
            get {
                return ResourceManager.GetString("ExportBtnExport", resourceCulture);
            }
        }

        internal static string ExportBtnCancel {
            get {
                return ResourceManager.GetString("ExportBtnCancel", resourceCulture);
            }
        }

        internal static string BleConnectionException {
            get {
                return ResourceManager.GetString("BleConnectionException", resourceCulture);
            }
        }

        internal static string StatusDeviceDiscovered {
            get {
                return ResourceManager.GetString("StatusDeviceDiscovered", resourceCulture);
            }
        }

        internal static string StatusDeviceAlreadyConnected {
            get {
                return ResourceManager.GetString("StatusDeviceAlreadyConnected", resourceCulture);
            }
        }

        internal static string StatusDeviceConnected {
            get {
                return ResourceManager.GetString("StatusDeviceConnected", resourceCulture);
            }
        }

        internal static string StatusDeviceDisconnected {
            get {
                return ResourceManager.GetString("StatusDeviceDisconnected", resourceCulture);
            }
        }

        internal static string StatusDeviceReconnected {
            get {
                return ResourceManager.GetString("StatusDeviceReconnected", resourceCulture);
            }
        }

        internal static string StatusDeviceReconnectFailed {
            get {
                return ResourceManager.GetString("StatusDeviceReconnectFailed", resourceCulture);
            }
        }

        internal static string StatusRecordingStarted {
            get {
                return ResourceManager.GetString("StatusRecordingStarted", resourceCulture);
            }
        }

        internal static string StatusRecordingStopped {
            get {
                return ResourceManager.GetString("StatusRecordingStopped", resourceCulture);
            }
        }

        internal static string StatusChartCleared {
            get {
                return ResourceManager.GetString("StatusChartCleared", resourceCulture);
            }
        }

        internal static string ConfirmDisconnect {
            get {
                return ResourceManager.GetString("ConfirmDisconnect", resourceCulture);
            }
        }

        internal static string StatusDeviceDisconnectedAction {
            get {
                return ResourceManager.GetString("StatusDeviceDisconnectedAction", resourceCulture);
            }
        }

        internal static string StatusDeviceDisconnectedAll {
            get {
                return ResourceManager.GetString("StatusDeviceDisconnectedAll", resourceCulture);
            }
        }

        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }

        internal static string ErrorExportFailed {
            get {
                return ResourceManager.GetString("ErrorExportFailed", resourceCulture);
            }
        }

        internal static string ConfirmCloseWithExport {
            get {
                return ResourceManager.GetString("ConfirmCloseWithExport", resourceCulture);
            }
        }
    }
}
